/** Shared grid and typography for public profile pages. */
export const modelDetailPageClasses = {
  kvGrid: "grid grid-cols-1 gap-px border border-[var(--color-line)] bg-[var(--color-line)] sm:grid-cols-2 sm:[&>*:last-child:nth-child(odd)]:col-span-2",
  kvItem: "min-w-0 bg-[var(--color-surface)] p-3 md:p-4",
  kvKey: "font-doc text-[10px] uppercase tracking-[0.1em] text-[var(--color-muted)] [overflow-wrap:anywhere]",
  kvValue: "mt-2 whitespace-pre-line font-doc text-[12px] leading-[1.65] text-[var(--color-ink)] [overflow-wrap:anywhere]",
  root: "min-w-0 space-y-4",
  topRow: "flex items-center justify-between gap-4",
  backLink: "font-doc text-[11px] uppercase tracking-[0.12em] text-[var(--color-muted)] hover:text-[var(--color-ink)]",
  contentWrap: "mx-auto min-w-0 max-w-[1540px]",
  mainGrid: "grid grid-cols-1 items-start border border-[var(--color-line)] bg-[var(--color-surface)] lg:grid-cols-[minmax(0,2fr)_minmax(0,3fr)]",
  mediaSection: "min-w-0 border-b border-[var(--color-line)] bg-[var(--color-paper)] lg:sticky lg:top-6 lg:border-b-0",
  hero: "relative aspect-square w-full overflow-hidden bg-[var(--color-paper)]",
  heroImage: "object-contain object-center",
  heroFallback: "flex h-full w-full items-center justify-center p-6 text-center font-doc text-[11px] uppercase tracking-[0.12em] text-[var(--color-muted)]",
  detailsSection: "min-w-0 bg-[var(--color-surface)] p-4 sm:p-6 lg:border-l lg:border-[var(--color-line)] xl:p-8",
  title: "font-doc text-[clamp(28px,4vw,56px)] leading-[1.08] uppercase tracking-[-0.04em] [overflow-wrap:anywhere]",
  meta: "mt-4 font-doc text-[10px] leading-relaxed uppercase tracking-[0.1em] text-[var(--color-muted)] [overflow-wrap:anywhere]",
  documentId: "mt-2 block text-[9px] tracking-[0.06em]",
  socialSection: "mt-6 empty:hidden",
  blocks: "mt-6 divide-y divide-[var(--color-line)] border-y border-[var(--color-line)]",
  block: "min-w-0 py-5",
  blockTitle: "font-doc text-[11px] uppercase tracking-[0.12em] text-[var(--color-muted)]",
  blockText: "mt-3 whitespace-pre-line font-doc text-[13px] leading-[1.8] [overflow-wrap:anywhere]",
  blockBody: "mt-3 min-w-0",
  actions: "mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2",
  actionPrimary: "flex min-h-12 min-w-0 items-center justify-center border border-black bg-black px-3 py-3 text-center font-doc text-[11px] uppercase leading-relaxed tracking-[0.08em] text-white hover:bg-neutral-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black",
  actionSecondary: "flex min-h-12 min-w-0 items-center justify-center border border-[var(--color-line)] bg-[var(--color-surface)] px-3 py-3 text-center font-doc text-[11px] uppercase leading-relaxed tracking-[0.08em] text-[var(--color-ink)] hover:bg-neutral-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black",
  gallerySection: "border-x border-b border-[var(--color-line)] bg-[var(--color-paper)] p-4 md:p-6",
  galleryGrid: "mx-auto grid grid-cols-1 items-start gap-4 sm:grid-cols-2",
  galleryItem: "relative aspect-[5/4] min-w-0 w-full overflow-hidden bg-[var(--color-paper)]",
  galleryItemSolo: "sm:col-span-2 sm:w-full sm:max-w-[1200px] sm:justify-self-center",
  galleryImage: "object-contain object-center",
  galleryFallback: "p-6 text-center font-doc text-[11px] uppercase tracking-[0.12em] text-[var(--color-muted)]"
} as const;
